import {makeQuote,deliveryPrice} from '../server/delivery.js';
import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import{readFileSync,readdirSync}from'node:fs';import{api,hash}from'../server/api.js';import{prices,promotions,priceItem}from'../public/catalog.js';import{encryptedPayload,un64,b64,validEndpoint}from'../server/push.js';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
const DB={prepare(q){const statement=(args=[])=>({bind(...values){return statement(values)},async first(){return sql.prepare(q).get(...args)||null},async all(){return{results:sql.prepare(q).all(...args)}},async run(){const r=sql.prepare(q).run(...args);return{meta:{changes:r.changes}}}});return statement()},async batch(items){sql.exec('BEGIN');try{const out=[];for(const item of items)out.push(await item.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
const testEmail='brunobrandao179@gmail.com',testCodes=Array.from({length:5},(_,i)=>'private-test-code-long-number-'+i);const env={DB,STAFF_ACCESS_CONFIG:JSON.stringify({accounts:[{email:testEmail,role:'admin',hashes:await Promise.all(testCodes.map(c=>hash(testEmail+'\0'+c)))}]})},pending=[],ctx={waitUntil(p){pending.push(p)}};
// Google responses are deterministic test doubles; no real addresses, orders or charges.
env.GOOGLE_MAPS_API_KEY='test-key-not-real';
sql.prepare("INSERT INTO section_settings(owner,section,data,updated) VALUES('store','delivery',?,1)").run(JSON.stringify({origin:{lat:-12.09,lng:-45.8}}));
let routeMeters=1900, mapsFail=false;
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,opts)=>{if(String(url).startsWith('https://maps.googleapis.com'))return Response.json({status:'OK',results:[{geometry:{location:{lat:-12.095,lng:-45.81},location_type:'ROOFTOP'},formatted_address:'Endereço de teste'}]});if(String(url).startsWith('https://routes.googleapis.com')){if(mapsFail)return new Response('',{status:503});return Response.json({routes:[{distanceMeters:routeMeters,duration:'300s'}]})}return originalFetch(url,opts)};
sql.prepare("INSERT INTO section_settings(owner,section,data,updated) VALUES('store','service',?,1)").run(JSON.stringify({accepting:true,eta:40,unavailable:[],promotion:{type:'percentage',value:10,name:'Desconto de inauguração',active:false}}));
let staffCookie='';
async function request(path,{method='GET',data,cookie='',uid='',token='',track='',driver='',guest='',slot=1,origin='https://test.example'}={}){if(uid==='owner')cookie=staffCookie;if(path==='/orders'&&method==='POST'&&data?.delivery==='delivery'&&!data.deliveryQuoteId&&!data.skipAutoQuote){const a=(await request('/customer/session',{cookie})).body.account;const own=a?'account:'+a.id:await hash(cookie.split('=')[1]||'');data={...data,deliveryQuoteId:(await makeQuote(env,own,data)).id}}const headers={'content-type':'application/json',origin,cookie,'cf-connecting-ip':'127.0.0.2'};if(guest)headers['x-atrevida-guest']=guest;if(uid){headers['oai-authenticated-user-id']=uid;headers['oai-authenticated-user-email']=uid+'@test.example'}if(token)headers['x-delivery-token']=token;if(track)headers['x-tracking-token']=track;if(driver){headers['x-driver-token']=driver;headers['x-driver-slot']=String(slot)}const response=await api(new Request('https://test.example/api'+path,{method,headers,body:method==='GET'?undefined:JSON.stringify(data||{})}),env,ctx);return{status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]}}
const cookieLess=await request('/session');assert.match(cookieLess.body.guestToken,/^[\w-]{43}$/);assert.equal((await request('/draft',{guest:cookieLess.body.guestToken})).status,200);assert.equal((await request('/draft',{guest:'bad'})).status,401);
const session=await request('/session');assert.match(session.cookie,/atrevida_customer=/);const cookie=session.cookie;const other=(await request('/session')).cookie;
const item={id:1,qty:1,size:'Grande',border:'Sem borda recheada'};const order={nonce:'nonce123456789012345',items:[item],customer:'Cliente Teste',phone:'77999990000',delivery:'delivery',payment:'Pix',street:'Rua Teste',number:'5',neighborhood:'Top Park'};
assert.equal((await request('/draft',{method:'PUT',cookie,data:{items:[item]}})).status,200);assert.equal((await request('/draft',{cookie})).body.items.length,1);
let result=await request('/orders',{method:'POST',cookie,data:order});assert.equal(result.status,201);assert.equal(result.body.order.known_total,5499);assert.match(result.body.whatsapp,/wa.me\/557798071769/);const id=result.body.order.id;
assert.equal((await request('/orders',{method:'POST',cookie,data:order})).body.order.id,id);assert.equal((await request('/orders',{cookie:other})).body.orders.length,0);assert.equal((await request('/orders/'+id,{cookie:other})).status,403);
assert.equal((await request('/staff/orders',{uid:'outsider'})).status,403);
const savedWA=await request('/orders/'+id+'/whatsapp',{cookie});assert.equal(savedWA.status,200);assert.match(decodeURIComponent(savedWA.body.whatsapp),/Cliente Teste/);assert.equal((await request('/orders/'+id+'/whatsapp',{cookie:other})).status,403);assert.equal((await request('/orders/'+id+'/whatsapp')).status,403);assert.equal(sql.prepare('SELECT count(*) AS n FROM orders WHERE id=?').get(id).n,1);

assert.equal((await request('/staff/login',{method:'POST',data:{email:'mrdigitalvip@gmail.com',code:testCodes[0]}})).status,403);
const login=await request('/staff/login',{method:'POST',data:{email:testEmail,code:testCodes[0]}});assert.equal(login.status,200);assert.equal(login.body.remaining,4);staffCookie=login.cookie;
assert.equal((await request('/staff/login',{method:'POST',data:{email:testEmail,code:testCodes[0]}})).status,403);
assert.equal((await request('/staff/claim',{method:'POST',uid:'outsider',data:{code:'old-code'}})).status,404);
assert.equal((await request('/staff/renew',{method:'POST',uid:'owner',data:{email:testEmail}})).status,409);
const status=async(s)=>request('/orders/'+id+'/status',{method:'POST',uid:'owner',data:{status:s,eta:40}});assert.equal((await status('onway')).status,409);assert.equal((await status('confirmed')).status,200);assert.equal((await status('preparing')).status,200);assert.equal((await status('ready')).status,200);
const link=(await request('/orders/'+id+'/courier',{method:'POST',uid:'owner'})).body.url;const token=link.split(':').at(-1);assert.equal((await request('/orders/'+id,{token:'wrong'})).status,403);assert.equal((await request('/orders/'+id,{token})).status,200);assert.equal((await request('/orders/'+id+'/status',{method:'POST',token,data:{status:'cancelled'}})).status,409);assert.equal((await request('/orders/'+id+'/status',{method:'POST',token,data:{status:'onway'}})).status,200);assert.equal((await request('/orders/'+id+'/status',{method:'POST',token,data:{status:'delivered'}})).status,200);
result=await request('/orders',{method:'POST',cookie,data:{...order,nonce:'nonce222222222222222',items:[{...item,second:40,border:'Cheddar'},{id:51,qty:1}],delivery:'pickup'}});assert.equal(result.status,201);assert.equal(result.body.order.known_total,8300);assert.equal(result.body.order.total,8300);const q=result.body.order.id;sql.prepare("UPDATE orders SET data=json_set(data,'$.pending',json('true')),total=NULL WHERE id=?").run(q);
assert.equal((await request('/orders/'+q+'/status',{method:'POST',uid:'owner',data:{status:'confirmed',eta:30}})).status,400);assert.equal((await request('/orders/'+q+'/status',{method:'POST',uid:'owner',data:{status:'quote',total:9000,eta:35}})).status,200);assert.equal((await request('/orders/'+q+'/approve',{method:'POST',cookie:other,data:{total:9000}})).status,403);assert.equal((await request('/orders/'+q+'/approve',{method:'POST',cookie,data:{total:7000}})).status,409);assert.equal((await request('/orders/'+q+'/approve',{method:'POST',cookie,data:{total:9000}})).status,200);
assert.equal((await request('/draft',{method:'PUT',cookie,origin:'https://evil.example',data:{items:[]}})).status,403);assert.equal((await request('/orders',{method:'POST',cookie,data:{...order,nonce:'nonce333333333333333',items:[{...item,qty:-1}]}})).status,400);
assert.deepEqual(prices[30],[44,52,60]);assert.deepEqual(prices[38],[43,53,62]);assert.deepEqual(prices[47],[40,50,58]);assert.equal(Object.keys(promotions).length,5);assert.equal(priceItem({...item,second:40}),6000);assert.equal(priceItem({...item,id:28}),5100);
// Independently decrypt RFC8291 payload to verify the push encryption round trip.
const ua=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),uaPublic=new Uint8Array(await crypto.subtle.exportKey('raw',ua.publicKey)),auth=crypto.getRandomValues(new Uint8Array(16));const payload={title:'Teste',body:'Pedido confirmado'};const encrypted=await encryptedPayload({keys:{p256dh:b64(uaPublic),auth:b64(auth)}},payload);const salt=encrypted.slice(0,16),as=encrypted.slice(21,86),cipher=encrypted.slice(86);const asKey=await crypto.subtle.importKey('raw',as,{name:'ECDH',namedCurve:'P-256'},false,[]);const shared=await crypto.subtle.deriveBits({name:'ECDH',public:asKey},ua.privateKey,256);const enc=new TextEncoder();const cat=(...xs)=>{const a=new Uint8Array(xs.reduce((n,x)=>n+x.length,0));let offset=0;for(const x of xs){a.set(x,offset);offset+=x.length}return a};const derive=async(secret,salt,info,n)=>crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info},await crypto.subtle.importKey('raw',secret,'HKDF',false,['deriveBits']),n*8);const ikm=await derive(shared,auth,cat(enc.encode('WebPush: info\0'),uaPublic,as),32);const cek=await derive(ikm,salt,enc.encode('Content-Encoding: aes128gcm\0'),16),nonce=await derive(ikm,salt,enc.encode('Content-Encoding: nonce\0'),12);const plaintext=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce},await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['decrypt']),cipher));assert.equal(plaintext.at(-1),2);assert.deepEqual(JSON.parse(new TextDecoder().decode(plaintext.slice(0,-1))),payload);assert.equal(validEndpoint('https://127.0.0.1/push'),false);assert.equal(validEndpoint('https://fcm.googleapis.com/fcm/send/test'),true);
await Promise.allSettled(pending);console.log('PASS: pricing, promotions, server totals, saved cart, idempotency, data isolation, owner invitation, transitions, courier permissions, quote approval, CSRF, validation and push encryption.');

assert.equal(priceItem({...item,border:'Cheddar'}),5600);
const stats=await request('/staff/orders',{uid:'owner'});assert.equal(stats.status,200);assert.equal(stats.body.stats.today,2);
// Full isolated scenario: staff records a scheduled order, shares tracking, assigns courier and completes delivery.
assert.equal((await request('/staff/clients')).status,403);
const manual=await request('/staff/manual',{method:'POST',uid:'owner',data:{...order,nonce:'manual123456789012345',manualDeliveryFee:899,items:[{...item,border:'Chocolate'}],scheduledAt:Date.now()+3600000,location:{lat:-12.09,lng:-45.8}}});assert.equal(manual.status,201);const manualId=manual.body.order.id;const repeatManual=await request('/staff/manual',{method:'POST',uid:'owner',data:{...order,nonce:'manual123456789012345',manualDeliveryFee:899,items:[item]}});assert.equal(repeatManual.body.order.id,manualId);assert.equal(manual.body.order.data.source,'manual');assert.equal(manual.body.order.known_total,6499);assert.match(manual.body.tracking,/acompanhar#/);
const tracking=(await request('/orders/'+manualId+'/tracking',{method:'POST',uid:'owner'})).body.url.split(':').at(-1);
let tracked=await request('/orders/'+manualId,{track:tracking});assert.equal(tracked.status,200);assert.equal(tracked.body.order.data.phone,undefined);assert.equal(tracked.body.order.data.location,undefined);
assert.equal((await request('/orders/'+manualId+'/status',{method:'POST',track:tracking,data:{status:'confirmed',eta:35}})).status,403);
assert.equal((await request('/orders/'+manualId+'/operations',{method:'POST',uid:'owner',data:{note:'Embalagem extra',courierName:'Entregador Teste',vehicle:'Moto'}})).status,200);
const deliveryLink=(await request('/orders/'+manualId+'/courier',{method:'POST',uid:'owner'})).body.url;const deliveryToken=deliveryLink.split(':').at(-1);
assert.equal((await request('/orders/'+manualId+'/courier-profile',{method:'POST',token:deliveryToken,data:{name:'José Teste',vehicle:'Moto azul'}})).status,200);
const courierData=await request('/orders/'+manualId,{token:deliveryToken});assert.equal(courierData.body.order.courierName,'José Teste');assert.equal(courierData.body.order.data.location.lat,-12.09);
for(const state of ['confirmed','preparing','ready'])assert.equal((await request('/orders/'+manualId+'/status',{method:'POST',uid:'owner',data:{status:state,eta:35}})).status,200);
assert.equal((await request('/orders/'+manualId+'/status',{method:'POST',token:deliveryToken,data:{status:'onway'}})).status,200);assert.equal((await request('/orders/'+manualId,{track:tracking})).body.order.status,'onway');
assert.equal((await request('/orders/'+manualId+'/status',{method:'POST',token:deliveryToken,data:{status:'delivered'}})).status,200);assert.deepEqual((await request('/orders/'+manualId,{token:deliveryToken})).body.order.data,{});
assert.equal((await request('/orders/'+manualId+'/courier-profile',{method:'POST',token:deliveryToken,data:{name:'Changed'}})).status,409);
assert.equal((await request('/staff/clients',{uid:'owner'})).body.clients.length>0,true);
console.log('PASS: scheduled manual order → private tracking → kitchen → assigned courier → delivery; GPS, customer privacy and terminal data restriction.');
for(const c of testCodes.slice(1)){const r=await request('/staff/login',{method:'POST',data:{email:testEmail,code:c}});assert.equal(r.status,200)}
assert.equal((await request('/staff/access',{uid:'owner'})).body.accounts[0].remaining,0);
const renewed=await request('/staff/renew',{method:'POST',uid:'owner',data:{email:testEmail}});assert.equal(renewed.status,200);assert.equal(renewed.body.codes.length,5);
assert.equal((await request('/staff/renew',{method:'POST',uid:'owner',data:{email:testEmail}})).status,409);
assert.equal((await request('/staff/logout',{method:'POST',uid:'owner'})).status,200);
assert.equal((await request('/staff/orders',{uid:'owner'})).status,403);
console.log('PASS: email allowlist, single-use codes, replay rejection, renewal authorization, remaining count, logout, dashboard and R$8 crust.');
// New production flows are exercised against an isolated database, never real customers.
staffCookie=(await request('/staff/login',{method:'POST',data:{email:testEmail,code:renewed.body.codes[0]}})).cookie;
const customerInfo={email:'test-client@example.com',name:'Cliente Clube',phone:'77999998888',password:'test-password-long-123',accepted:true};
const registration=await request('/customer/register',{method:'POST',data:customerInfo});assert.equal(registration.status,200);assert.ok(registration.body.recoveryCode);assert.equal(registration.body.account.password,undefined);const accountCookie=registration.cookie;
assert.equal((await request('/customer/login',{method:'POST',data:{...customerInfo,password:'wrong-password-123'}})).status,403);
assert.equal((await request('/customer/login',{method:'POST',data:customerInfo})).status,200);
assert.equal((await request('/customer/session',{cookie:accountCookie})).body.deliveryFee,699);
assert.equal((await request('/customer/session')).body.deliveryFee,899);
assert.equal((await request('/staff/accounts',{uid:'owner'})).body.accounts[0].email,customerInfo.email);
const clubOrder={...order,nonce:'club-order-number-0001',expectedDeliveryFee:699};
const club=await request('/orders',{method:'POST',cookie:accountCookie,data:clubOrder});assert.equal(club.status,201);assert.equal(club.body.order.total,5499);assert.equal(club.body.order.data.deliveryFee,699);const clubId=club.body.order.id;
assert.equal((await request('/orders',{method:'POST',cookie:accountCookie,data:{...clubOrder,nonce:'club-order-wrong-fee',expectedDeliveryFee:0}})).status,409);
for(let slot=1;slot<=4;slot++)assert.equal((await request('/staff/drivers/'+slot,{method:'PUT',uid:'owner',data:{name:'Motorista '+slot,phone:'77999990000',vehicle:'Moto '+slot,active:true}})).status,200);
assert.equal((await request('/staff/drivers/5',{method:'PUT',uid:'owner',data:{name:'Quinto'}})).status,404);
const driverToken=(await request('/staff/drivers/1/link',{method:'POST',uid:'owner'})).body.url.split(':').at(-1);
assert.equal((await request('/driver',{driver:driverToken})).status,200);
assert.equal((await request('/orders/'+clubId,{driver:driverToken})).status,403);
assert.equal((await request('/orders/'+clubId+'/assign',{method:'POST',uid:'owner',data:{slot:1}})).status,200);
assert.equal((await request('/driver',{driver:driverToken})).body.orders.length,1);
assert.equal((await request('/driver/profile',{method:'PUT',driver:driverToken,data:{name:'João',vehicle:'Moto preta'}})).status,200);
assert.equal((await request('/driver',{driver:driverToken})).body.profile.name,'João');
assert.equal((await request('/orders/'+clubId+'/status',{method:'POST',driver:driverToken,data:{status:'confirmed',eta:30}})).status,409);
for(const state of ['confirmed','preparing','ready'])assert.equal((await request('/orders/'+clubId+'/status',{method:'POST',uid:'owner',data:{status:state,eta:30}})).status,200);
assert.equal((await request('/orders/'+clubId+'/payment',{method:'POST',uid:'owner',data:{received:true,method:'Pix',amount:5499}})).status,200);
for(const state of ['onway','delivered'])assert.equal((await request('/orders/'+clubId+'/status',{method:'POST',driver:driverToken,data:{status:state}})).status,200);
let wallet=(await request('/customer/session',{cookie:accountCookie})).body.wallet;assert.equal(wallet.balance,144);assert.equal(wallet.completed,1);
assert.equal((await request('/orders/'+clubId+'/status',{method:'POST',driver:driverToken,data:{status:'delivered'}})).status,409);
assert.deepEqual((await request('/driver',{driver:driverToken})).body.orders[0].data,{});
// Four more purchases; advance them through the actual operation API.
for(let n=2;n<=5;n++){sql.exec('DELETE FROM rate_limits');const r=await request('/orders',{method:'POST',cookie:accountCookie,data:{...clubOrder,nonce:'club-purchase-number-'+n}});assert.equal(r.status,201);for(const state of ['confirmed','preparing','ready','onway','delivered'])assert.equal((await request('/orders/'+r.body.order.id+'/status',{method:'POST',uid:'owner',data:{status:state,eta:30}})).status,200);assert.equal((await request('/orders/'+r.body.order.id+'/payment',{method:'POST',uid:'owner',data:{received:true,method:'Pix',amount:r.body.order.total}})).status,200)}
wallet=(await request('/customer/session',{cookie:accountCookie})).body.wallet;assert.equal(wallet.completed,5);assert.equal(wallet.balance,720);
const redeem=await request('/orders',{method:'POST',cookie:accountCookie,data:{...clubOrder,nonce:'club-redeem-number-six',useCashback:true}});assert.equal(redeem.status,201);assert.equal(redeem.body.order.total,4779);assert.equal(redeem.body.order.data.cashbackUsed,720);assert.equal((await request('/customer/session',{cookie:accountCookie})).body.wallet.balance,0);
assert.equal((await request('/orders',{method:'POST',cookie:accountCookie,data:{...clubOrder,nonce:'club-redeem-number-six',useCashback:true}})).body.order.id,redeem.body.order.id);
assert.equal((await request('/orders/'+redeem.body.order.id+'/status',{method:'POST',uid:'owner',data:{status:'cancelled'}})).status,200);assert.equal((await request('/customer/session',{cookie:accountCookie})).body.wallet.balance,720);
assert.equal((await request('/staff/preferences/orders',{method:'PUT',uid:'owner',data:{title:'Minha operação',accent:'blue',compact:true}})).status,200);assert.equal((await request('/staff/preferences',{uid:'owner'})).body.settings.orders.title,'Minha operação');assert.equal((await request('/staff/preferences')).status,403);
const recovered=await request('/customer/recover',{method:'POST',data:{email:customerInfo.email,password:'new-customer-password-123',recovery:registration.body.recoveryCode}});assert.equal(recovered.status,200);assert.equal((await request('/customer/session',{cookie:accountCookie})).body.account,null);assert.equal((await request('/customer/recover',{method:'POST',data:{email:customerInfo.email,password:'new-customer-password-123',recovery:registration.body.recoveryCode}})).status,403);
const oldDriver=driverToken;await request('/staff/drivers/1/link',{method:'POST',uid:'owner'});assert.equal((await request('/driver',{driver:oldDriver})).status,403);
console.log('PASS: optional customer account, password and recovery, distance-based delivery quotes, 4 drivers, scoped live delivery, preferences persistence, customer roster, 5 completed purchases, 3% cashback credit, redeem reservation, duplicate prevention and cancellation refund.');
// Store control and public courier identity are permission-bound.
assert.equal((await request('/storefront')).body.accepting,true);
assert.equal((await request('/staff/store',{method:'PUT',data:{accepting:false,eta:40,unavailable:[]}})).status,403);
assert.equal((await request('/staff/store',{method:'PUT',uid:'owner',data:{accepting:false,eta:50,unavailable:[]}})).status,200);
sql.exec('DELETE FROM rate_limits');
const freshCookie=(await request('/session')).cookie;
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...order,nonce:'paused-store-test-123'}})).status,409);
assert.equal((await request('/staff/store',{method:'PUT',uid:'owner',data:{accepting:true,eta:50,unavailable:[40]}})).status,200);
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...order,nonce:'unavailable-half-test-123',items:[{...item,second:40}]}})).status,409);
await request('/staff/store',{method:'PUT',uid:'owner',data:{accepting:true,eta:40,unavailable:[]}});
const photoOrder=await request('/orders',{method:'POST',cookie:freshCookie,data:{...order,nonce:'courier-photo-test-123'}});assert.equal(photoOrder.status,201);const photoOrderId=photoOrder.body.order.id;
await request('/orders/'+photoOrderId+'/assign',{method:'POST',uid:'owner',data:{slot:1}});
assert.equal((await request('/orders/'+photoOrderId,{cookie:freshCookie})).body.order.courier,null);
for(const state of ['confirmed','preparing','ready'])assert.equal((await request('/orders/'+photoOrderId+'/status',{method:'POST',uid:'owner',data:{status:state,eta:40}})).status,200);
const publicDriver=(await request('/orders/'+photoOrderId,{cookie:freshCookie})).body.order.courier;assert.equal(publicDriver.name,'João');assert.equal(publicDriver.vehicle,'Moto preta');assert.equal(publicDriver.phone,undefined);assert.equal(publicDriver.token_hash,undefined);
assert.equal((await request('/orders/'+photoOrderId+'/driver-photo',{cookie:other})).status,403);
const imageBytes=new Uint8Array([255,216,255,217]);env.UPLOADS={async get(){return{body:imageBytes}}};sql.prepare("UPDATE drivers SET photo_key='test-photo.jpg' WHERE slot=1").run();
const photoResponse=await api(new Request('https://test.example/api/orders/'+photoOrderId+'/driver-photo',{headers:{cookie:freshCookie}}),env,ctx);assert.equal(photoResponse.status,200);assert.equal(photoResponse.headers.get('content-type'),'image/jpeg');assert.deepEqual(new Uint8Array(await photoResponse.arrayBuffer()),imageBytes);
assert.equal((await request('/staff/insights')).status,403);assert.ok((await request('/staff/insights',{uid:'owner'})).body.days.length);
console.log('PASS: store pause, unavailable half-pizza rejection, staff-only controls/insights, courier identity only when ready/onway, protected photo and no driver contact/token disclosure.');

// Quote is tied to session, exact address, configuration revision, and expiry.
sql.exec('DELETE FROM rate_limits');
assert.deepEqual(deliveryPrice(2000),{base:699,fee:699,discount:0});assert.equal(deliveryPrice(2001).fee,999);assert.equal(deliveryPrice(12000).fee,1799);assert.equal(deliveryPrice(4000,true).fee,799);assert.equal(deliveryPrice(1000,true).fee,699);assert.throws(()=>deliveryPrice(12001));
const quote=await request('/delivery/quote',{method:'POST',cookie:freshCookie,data:order});assert.equal(quote.status,200);assert.equal(quote.body.distanceMeters,1900);assert.equal(quote.body.fee,699);assert.equal(quote.body.addressHash,undefined);
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...order,nonce:crypto.randomUUID(),deliveryQuoteId:quote.body.id,number:'999'}})).status,409);
assert.equal((await request('/orders',{method:'POST',cookie:other,data:{...order,nonce:crypto.randomUUID(),deliveryQuoteId:quote.body.id}})).status,409);
const own=await hash(freshCookie.split('=')[1]);sql.prepare("UPDATE section_settings SET data=json_set(data,'$.expires',0) WHERE owner=? AND section='delivery_quote'").run(own);
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...order,nonce:crypto.randomUUID(),deliveryQuoteId:quote.body.id}})).status,409);
mapsFail=true;assert.equal((await request('/delivery/quote',{method:'POST',cookie:freshCookie,data:order})).status,503);mapsFail=false;
delete env.GOOGLE_MAPS_API_KEY;
sql.exec('DELETE FROM rate_limits');
const manualQuote=await request('/delivery/quote',{method:'POST',cookie:freshCookie,data:order});assert.equal(manualQuote.status,200);assert.equal(manualQuote.body.fee,null);assert.equal(manualQuote.body.pending,true);assert.equal(manualQuote.body.distanceMeters,null);
const manualData={...order,nonce:crypto.randomUUID(),channel:'whatsapp',complement:'Quadra N lote 5',deliveryQuoteId:manualQuote.body.id,expectedDeliveryFee:null};
const manualSale=await request('/orders',{method:'POST',cookie:freshCookie,data:manualData});assert.equal(manualSale.status,201);assert.equal(manualSale.body.order.total,null);assert.equal(manualSale.body.order.data.deliveryPending,true);assert.match(decodeURIComponent(manualSale.body.whatsapp),/A confirmar pela pizzaria/);assert.match(decodeURIComponent(manualSale.body.whatsapp),/Quadra N lote 5/);assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:manualData})).body.order.id,manualSale.body.order.id);
const mid=manualSale.body.order.id;await Promise.allSettled(pending);assert.equal(sql.prepare('SELECT count(*) AS n FROM print_jobs WHERE order_id=?').get(mid).n,0);
assert.equal((await request('/orders/'+mid+'/status',{method:'POST',uid:'owner',data:{status:'confirmed',eta:40}})).status,400);
assert.equal((await request('/orders/'+mid+'/status',{method:'POST',uid:'owner',data:{status:'quote',deliveryFee:10,eta:40}})).status,400);
assert.equal((await request('/orders/'+mid+'/status',{method:'POST',uid:'owner',data:{status:'quote',deliveryFee:1799,eta:40}})).status,200);
const quoted=(await request('/orders/'+mid,{cookie:freshCookie})).body.order;assert.equal(quoted.total,quoted.known_total+1799);assert.equal(quoted.data.deliveryFee,1799);
assert.equal((await request('/orders/'+mid+'/manual-approve',{method:'POST',uid:'owner',data:{total:quoted.total,accepted:true}})).status,200);
for(const status of ['preparing','ready'])assert.equal((await request('/orders/'+mid+'/status',{method:'POST',uid:'owner',data:{status}})).status,200);
const mlink=(await request('/orders/'+mid+'/courier',{method:'POST',uid:'owner'})).body.url;const mtoken=mlink.split(':').at(-1);
for(const status of ['onway','delivered'])assert.equal((await request('/orders/'+mid+'/status',{method:'POST',token:mtoken,data:{status}})).status,200);
sql.exec('DELETE FROM rate_limits');
const noCookieQuote=await request('/delivery/quote',{method:'POST',guest:cookieLess.body.guestToken,data:order});assert.equal(noCookieQuote.status,200);
const noCookieOrder=await request('/orders',{method:'POST',guest:cookieLess.body.guestToken,data:{...order,nonce:crypto.randomUUID(),payment:'Pix na entrega',deliveryQuoteId:noCookieQuote.body.id}});assert.equal(noCookieOrder.status,201);assert.equal(noCookieOrder.body.order.data.paymentStatus,'pending');assert.equal((await request('/orders/'+noCookieOrder.body.order.id,{guest:cookieLess.body.guestToken})).status,200);assert.equal((await request('/orders/'+noCookieOrder.body.order.id,{guest:'A'.repeat(43)})).status,403);
console.log('PASS: no-map delivery → complete WhatsApp message → one saved order → private fee quote → customer approval recorded → kitchen → scoped courier delivery.');

console.log('PASS: road-distance fee tiers, member floor, range limit, expired/changed/foreign quote rejection, map outage and no-map delivery pending staff confirmation.');
// Final inauguration / offline / payment / print acceptance against isolated adapters.
const {calculateTotals}=await import('../public/pricing.js');
const {initializePayment,applyPaymentNotification,verifyWebhook,paymentConfig}=await import('../server/payments.js');
const {enqueuePrint,cloudPrint,printerConfig}=await import('../server/printing.js');
assert.equal(calculateTotals(10000,899).total,9899);assert.equal(calculateTotals(8000,999).total,8199);
await request('/staff/store',{method:'PUT',uid:'owner',data:{accepting:true,eta:40,unavailable:[],promotionActive:true}});
sql.exec('DELETE FROM rate_limits');
const finalData={...order,nonce:crypto.randomUUID(),delivery:'pickup',payment:'Dinheiro na entrega',change:'100,00',items:[{...item,second:40,border:'Catupiry'},{id:51,qty:2}]};
const finalOrder=await request('/orders',{method:'POST',cookie:freshCookie,data:finalData});assert.equal(finalOrder.status,201);assert.equal(finalOrder.body.order.data.subtotal,9800);assert.equal(finalOrder.body.order.data.promotionDiscount,980);assert.equal(finalOrder.body.order.total,8820);assert.equal(finalOrder.body.order.data.changeFor,10000);assert.equal(finalOrder.body.order.data.paymentStatus,'pending');
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:finalData})).body.order.id,finalOrder.body.order.id);
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...finalData,nonce:crypto.randomUUID(),items:[{id:63,qty:1}],adult:false}})).status,400);
const alcohol=await request('/orders',{method:'POST',cookie:freshCookie,data:{...finalData,nonce:crypto.randomUUID(),payment:'Pix na entrega',items:[{id:63,qty:1}],adult:true}});assert.equal(alcohol.status,201);assert.equal(alcohol.body.order.total,360);assert.equal(alcohol.body.order.data.adultRequired,true);
assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:{...finalData,nonce:crypto.randomUUID(),items:[{id:55,qty:1}],adult:true}})).status,400);
// Snapshot survives promotion change.
await request('/staff/store',{method:'PUT',uid:'owner',data:{accepting:true,eta:40,unavailable:[],promotionActive:false}});assert.equal((await request('/orders/'+finalOrder.body.order.id,{cookie:freshCookie})).body.order.total,8820);
assert.equal(paymentConfig(env).status,'CONFIGURATION_REQUIRED');assert.equal(printerConfig(env).status,'CONFIGURATION_REQUIRED');
await Promise.allSettled(pending);const saved=await DB.prepare('SELECT * FROM orders WHERE id=?').bind(finalOrder.body.order.id).first();await enqueuePrint(env,saved);await enqueuePrint(env,saved);assert.equal(sql.prepare('SELECT count(*) AS n FROM print_jobs WHERE order_id=?').get(saved.id).n,2);assert.equal(sql.prepare("SELECT count(*) AS n FROM print_jobs WHERE status='PRINTED'").get().n,0);
env.CLOUDPRNT_USERNAME='test-printer';env.CLOUDPRNT_PASSWORD='test-password';env.CLOUDPRNT_MAC='aa:bb:cc:dd:ee:ff';const printerHeaders={authorization:'Basic '+btoa('test-printer:test-password'),'content-type':'application/json'};
const printerRequest=(method,query='',data)=>cloudPrint(new Request('https://test.example/api/printer/cloudprnt'+query,{method,headers:printerHeaders,body:method==='POST'?JSON.stringify(data):undefined}),env);
assert.equal((await (await printerRequest('POST','',{printerMAC:env.CLOUDPRNT_MAC,statusCode:'500 Printer Offline'})).json()).jobReady,false);
let pj=await (await printerRequest('POST','',{printerMAC:env.CLOUDPRNT_MAC,statusCode:'200 OK'})).json();assert.equal(pj.jobReady,true);assert.match(await (await printerRequest('GET','?token='+pj.jobToken)).text(),/ATREVIDA PIZZARIA/);await printerRequest('DELETE','?token='+pj.jobToken+'&code=500');assert.equal(sql.prepare('SELECT status FROM print_jobs WHERE lease=?').get(pj.jobToken).status,'FAILED');
const failed=sql.prepare('SELECT id FROM print_jobs WHERE lease=?').get(pj.jobToken);assert.equal((await request('/staff/print/'+failed.id+'/retry',{method:'POST',uid:'owner',data:{confirmed:true}})).status,200);sql.prepare('UPDATE print_jobs SET next_attempt=0 WHERE id=?').run(failed.id);pj=await (await printerRequest('POST','',{printerMAC:env.CLOUDPRNT_MAC,statusCode:'200 OK'})).json();await printerRequest('DELETE','?token='+pj.jobToken+'&code=200');await printerRequest('DELETE','?token='+pj.jobToken+'&code=200');assert.equal(sql.prepare('SELECT status FROM print_jobs WHERE lease=?').get(pj.jobToken).status,'PRINTED');
// Payment provider adapter double: this is NOT a Mercado Pago sandbox transaction.
env.MERCADOPAGO_PUBLIC_KEY='TEST-public';env.MERCADOPAGO_ACCESS_TOKEN='TEST-private';env.MERCADOPAGO_WEBHOOK_SECRET='test-signature-secret';env.PAYMENT_PUBLIC_ORIGIN='https://test.example';
let providerStatus='pending',providerPayment,creates=0;const beforeMP=globalThis.fetch;
globalThis.fetch=async(url,options={})=>{if(!String(url).startsWith('https://api.mercadopago.com'))return beforeMP(url,options);if(options.method==='POST'){creates++;const p=JSON.parse(options.body);providerPayment={id:123455+creates,external_reference:p.external_reference,metadata:p.metadata,transaction_amount:p.transaction_amount,currency_id:'BRL',status:providerStatus,date_last_updated:new Date().toISOString(),point_of_interaction:{transaction_data:{qr_code:'test-pix-code',qr_code_base64:'dGVzdA=='}}};return Response.json(providerPayment)}return Response.json({...providerPayment,status:providerStatus,date_last_updated:new Date().toISOString()})};
sql.exec('DELETE FROM rate_limits');const on=await request('/orders',{method:'POST',cookie:freshCookie,data:{...finalData,nonce:crypto.randomUUID(),payment:'Pix online',change:''}});assert.equal(on.status,201);const onlineRow=await DB.prepare('SELECT * FROM orders WHERE id=?').bind(on.body.order.id).first();assert.equal((await request('/orders/'+onlineRow.id+'/status',{method:'POST',uid:'owner',data:{status:'confirmed',eta:30}})).status,409);const form={formData:{payer:{email:'test@example.com'}}};let pay=await initializePayment(env,onlineRow,form);assert.equal(pay.status,'pending');assert.ok(pay.qr);await initializePayment(env,onlineRow,form);assert.equal(creates,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM print_jobs WHERE order_id=?').get(onlineRow.id).n,0);
const ts=String(Math.floor(Date.now()/1000)),rid='test-request';const hkey=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.MERCADOPAGO_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',hkey,new TextEncoder().encode(`id:123456;request-id:${rid};ts:${ts};`));const signature=Buffer.from(digest).toString('hex');const hook=new Request('https://test.example/api/payments/webhook?data.id=123456',{method:'POST',headers:{'x-signature':`ts=${ts},v1=${signature}`,'x-request-id':rid}});assert.equal(await verifyWebhook(hook,env),'123456');await assert.rejects(()=>verifyWebhook(new Request(hook.url,{method:'POST'}),env));providerStatus='approved';assert.equal((await api(hook,env,ctx)).status,200);assert.equal((await request('/orders/'+onlineRow.id,{cookie:freshCookie})).body.order.data.paymentStatus,'paid');assert.equal(sql.prepare('SELECT count(*) AS n FROM print_jobs WHERE order_id=?').get(onlineRow.id).n,2);await api(new Request(hook.url,{method:'POST',headers:hook.headers}),env,ctx);assert.equal(sql.prepare('SELECT count(*) AS n FROM print_jobs WHERE order_id=?').get(onlineRow.id).n,2);
providerStatus='rejected';sql.exec('DELETE FROM rate_limits');const card=await request('/orders',{method:'POST',cookie:freshCookie,data:{...finalData,nonce:crypto.randomUUID(),payment:'Cartão online',change:''}});const cardRow=await DB.prepare('SELECT * FROM orders WHERE id=?').bind(card.body.order.id).first();const cardResult=await initializePayment(env,cardRow,{formData:{token:'test-token-only',payment_method_id:'visa',installments:1,payer:{email:'test@example.com'}}});assert.equal(cardResult.status,'rejected');assert.equal((await request('/orders/'+cardRow.id,{cookie:freshCookie})).body.order.data.paymentStatus,'pending');
console.log('PASS: inauguration totals/snapshots, definitive prices, cash change, card-on-delivery, alcohol guard, disabled unconfirmed drink, payment config state, Pix/card adapter doubles, signed/invalid/duplicate webhooks, unpaid-online guard, durable print queue, offline printer, explicit retry, acknowledgement-only PRINTED.');
// WhatsApp checkout persists in one POST, without a separate quote request.
delete env.GOOGLE_MAPS_API_KEY;sql.exec('DELETE FROM rate_limits');
const onePostData={...finalData,nonce:crypto.randomUUID(),skipAutoQuote:true,deliveryQuoteId:undefined,delivery:'delivery',street:'Rua I',number:'5',neighborhood:'Top Park',channel:'whatsapp',payment:'Pix na entrega',change:'',expectedDeliveryFee:null,expectedTotal:undefined};
const onePost=await request('/orders',{method:'POST',cookie:freshCookie,data:onePostData});assert.equal(onePost.status,201,JSON.stringify(onePost.body));assert.equal(onePost.body.order.data.deliveryPending,true);assert.equal(onePost.body.order.data.channel,'whatsapp');assert.equal((await request('/orders',{method:'POST',cookie:freshCookie,data:onePostData})).body.order.id,onePost.body.order.id);assert.ok((await request('/orders/'+onePost.body.order.id,{uid:'owner'})).body.order);
console.log('PASS: single POST WhatsApp order without maps or prior quote → persisted order → staff access → retry returns same order.');
