import {b64,notify} from './push.js';
const now=()=>Date.now();
export const digest=async s=>b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
const random=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
const emailOf=s=>String(s||'').trim().toLowerCase();
const reject=(status,message)=>{throw Object.assign(Error(message),{status})};
const reply=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json','cache-control':'no-store',...headers}});
const cfg=env=>JSON.parse(env.STAFF_ACCESS_CONFIG||'{"accounts":[]}');
const bootstrap=[
 {email:'brunobrandao179@gmail.com',name:'Bruno Brandão',role:'admin',pinSalt:'YA9bc-vfSAAFLBSO5lGOkA',pinHash:'EL1qAj5lPL4j7AaTlni4SNJLVVev9rWA07R-o1OWTHE',bootstrap:true},
 {email:'majumello135@gmail.com',name:'Admin Atrevida',role:'admin',pinSalt:'3CwqNWfkKj1iqJSevKkwSQ',pinHash:'661AT--GTFA7LWZQEPleIyUhcMRBPJevKyo6xZne8ok',bootstrap:true}
];
const legacyAllowed=(env,email)=>{const normalized=emailOf(email);const raw=cfg(env).accounts.find(a=>emailOf(a.email)===normalized);return raw?{...raw,email:normalized,sourceEmail:String(raw.email||'').trim(),legacy:true}:undefined};
export const allowed=legacyAllowed;
const tokenOf=req=>(/^[\w-]{43}$/.test(req.headers.get('x-atrevida-staff')||'')?req.headers.get('x-atrevida-staff'):null)||req.headers.get('cookie')?.match(/(?:^|;\s*)atrevida_staff=([\w-]{43})(?:;|$)/)?.[1];
const pinDigest=(salt,email,pin)=>digest(String(salt)+'\0'+emailOf(email)+'\0'+String(pin||'').trim());
async function dynamicAccounts(env){const row=await env.DB.prepare("SELECT data FROM section_settings WHERE owner='store' AND section='staff_access'").first();if(!row)return[];try{const v=JSON.parse(row.data);return Array.isArray(v)?v:[]}catch{return[]}}
async function saveDynamicAccounts(env,accounts){await env.DB.prepare("INSERT INTO section_settings(owner,section,data,updated) VALUES('store','staff_access',?,?) ON CONFLICT(owner,section) DO UPDATE SET data=excluded.data,updated=excluded.updated").bind(JSON.stringify(accounts),now()).run()}
async function accountFor(env,email){const normalized=emailOf(email),dynamic=(await dynamicAccounts(env)).find(a=>emailOf(a.email)===normalized&&a.active!==false);if(dynamic)return{...dynamic,email:normalized};const built=bootstrap.find(a=>a.email===normalized);if(built)return built;return legacyAllowed(env,normalized)}
async function allAccounts(env){const dynamic=await dynamicAccounts(env),map=new Map();for(const a of bootstrap)map.set(a.email,{email:a.email,name:a.name,role:a.role,active:true,bootstrap:true});for(const a of cfg(env).accounts){const email=emailOf(a.email);if(email&&!map.has(email))map.set(email,{email,name:a.name||email,role:a.role||'staff',active:true,legacy:true})}for(const a of dynamic){const email=emailOf(a.email);if(email&&!bootstrap.some(b=>b.email===email))map.set(email,{email,name:a.name||email,role:a.role||'staff',active:a.active!==false})}return[...map.values()]}
async function seed(env){const tasks=[];for(const raw of cfg(env).accounts){const email=emailOf(raw.email);if(!email||!Array.isArray(raw.hashes))continue;tasks.push(env.DB.prepare('INSERT OR IGNORE INTO access_batches (id,email,generation,created) VALUES (?,?,0,?)').bind(email+':0',email,now()));for(const h of raw.hashes)tasks.push(env.DB.prepare('INSERT OR IGNORE INTO access_codes (hash,email,batch,used) VALUES (?,?,?,NULL)').bind(h,email,email+':0'))}if(tasks.length)await env.DB.batch(tasks);await recoverAccess(env)}
async function recoverAccess(env){if(!env.STAFF_ACCESS_RECOVERY_CONFIG)return;const r=JSON.parse(env.STAFF_ACCESS_RECOVERY_CONFIG),email=emailOf(r.email);if(!legacyAllowed(env,email)||!/^recovery:[\w-]{20,80}$/.test(r.id||'')||!Array.isArray(r.hashes)||r.hashes.length!==5||new Set(r.hashes).size!==5||r.hashes.some(h=>!/^[-\w]{43}$/.test(h)))throw Error('Invalid access recovery configuration');if(await env.DB.prepare('SELECT id FROM access_batches WHERE id=?').bind(r.id).first())return;await env.DB.batch([env.DB.prepare('UPDATE access_codes SET used=? WHERE lower(email)=? AND used IS NULL AND NOT EXISTS (SELECT 1 FROM access_batches WHERE id=?)').bind('revoked:'+r.id,email,r.id),env.DB.prepare('INSERT OR IGNORE INTO access_batches (id,email,generation,created) SELECT ?,?,COALESCE(MAX(generation),0)+1,? FROM access_batches WHERE lower(email)=?').bind(r.id,email,now(),email),...r.hashes.map(h=>env.DB.prepare('INSERT OR IGNORE INTO access_codes (hash,email,batch,used) VALUES (?,?,?,NULL)').bind(h,email,r.id))])}
export async function member(req,env){const token=tokenOf(req);if(!token)return null;const row=await env.DB.prepare('SELECT email,expires FROM staff_sessions WHERE hash=? AND expires>?').bind(await digest(token),now()).first();if(!row)return null;const a=await accountFor(env,row.email);return a?{id:'email:'+emailOf(a.email),email:emailOf(a.email),name:a.name||'',role:a.role||'staff',expires:row.expires}:null}
async function limit(env,key,max){const t=Math.floor(now()/600000);const r=await env.DB.prepare('INSERT INTO rate_limits (key,count,window) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window RETURNING count').bind(key,t).first();if(r.count>max)reject(429,'Muitas tentativas. Aguarde 10 minutos e tente novamente.')}
const remaining=async(env,email)=>(await env.DB.prepare('SELECT count(*) AS n FROM access_codes WHERE lower(email)=? AND used IS NULL').bind(emailOf(email)).first()).n;
const makePin=()=>String(100000+(crypto.getRandomValues(new Uint32Array(1))[0]%900000));
async function createSession(env,email,maxAge=2592000){const token=random(),sessionHash=await digest(token),t=now(),expires=t+maxAge*1000;await env.DB.prepare('INSERT INTO staff_sessions (hash,email,expires) VALUES (?,?,?)').bind(sessionHash,emailOf(email),expires).run();return{token,expires}}
export async function access(req,env,ctx,path,body){
 if(path==='/staff/login'&&req.method==='POST'){
  await limit(env,'login-ip:'+await digest(req.headers.get('cf-connecting-ip')||'unknown'),30);const b=await body(req),email=emailOf(b.email);await limit(env,'login-email:'+await digest(email),10);await seed(env);
  if(/^\d{6}$/.test(String(b.pin||'').trim())){const account=await accountFor(env,email);if(!account||!account.pinHash||await pinDigest(account.pinSalt,email,b.pin)!==account.pinHash)reject(403,'E-mail ou PIN incorreto, ou acesso ainda não autorizado.');const s=await createSession(env,email);return reply({ok:true,staffToken:s.token,expires:s.expires},200,{'set-cookie':`atrevida_staff=${s.token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`})}
  const code=String(b.code||'').trim(),account=legacyAllowed(env,email);if(!account||code.length<20||code.length>120)reject(403,'E-mail ou PIN incorreto, ou acesso ainda não autorizado.');const hashInputs=[email+'\0'+code];if(account.sourceEmail&&account.sourceEmail!==email)hashInputs.push(account.sourceEmail+'\0'+code);const hashes=await Promise.all(hashInputs.map(digest)),token=random(),sessionHash=await digest(token),t=now();let changed=0;for(const h of hashes){const result=await env.DB.prepare('UPDATE access_codes SET used=? WHERE hash=? AND lower(email)=? AND used IS NULL').bind(sessionHash,h,email).run();changed+=result.meta.changes;if(changed)break}if(!changed)reject(403,'E-mail ou PIN incorreto, ou acesso ainda não autorizado.');await env.DB.prepare('INSERT INTO staff_sessions (hash,email,expires) VALUES (?,?,?)').bind(sessionHash,email,t+43200000).run();return reply({ok:true,staffToken:token,expires:t+43200000},200,{'set-cookie':`atrevida_staff=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`})
 }
 if(path==='/staff/logout'&&req.method==='POST'){const token=tokenOf(req);if(token)await env.DB.prepare('DELETE FROM staff_sessions WHERE hash=?').bind(await digest(token)).run();return reply({ok:true},200,{'set-cookie':'atrevida_staff=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'})}
 if(path==='/staff/access'&&req.method==='GET'){const s=await member(req,env);if(!s)reject(403,'Entre na área privada');const accounts=await allAccounts(env);return reply({accounts:accounts.map(a=>({...a,remaining:0})),canManage:s.role==='admin',canRenew:false,expires:s.expires})}
 if(path==='/staff/access/grant'&&req.method==='POST'){const s=await member(req,env);if(!s||s.role!=='admin')reject(403,'Somente administradores podem liberar acessos.');const b=await body(req),email=emailOf(b.email),name=String(b.name||'').trim().slice(0,80),role=['admin','staff','kitchen','delivery'].includes(b.role)?b.role:'staff';if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))reject(400,'Informe um e-mail válido.');if(bootstrap.some(a=>a.email===email))reject(409,'Este administrador já possui acesso.');let accounts=await dynamicAccounts(env);if(accounts.some(a=>emailOf(a.email)===email&&a.active!==false))reject(409,'Este e-mail já possui acesso.');const pin=makePin(),pinSalt=random(),pinHash=await pinDigest(pinSalt,email,pin);accounts=accounts.filter(a=>emailOf(a.email)!==email);accounts.push({email,name:name||email,role,pinSalt,pinHash,active:true,created:now(),createdBy:s.email});await saveDynamicAccounts(env,accounts);return reply({ok:true,email,name:name||email,role,pin})}
 const revoke=path.match(/^\/staff\/access\/([^/]+)\/revoke$/);if(revoke&&req.method==='POST'){const s=await member(req,env);if(!s||s.role!=='admin')reject(403,'Somente administradores podem remover acessos.');const email=emailOf(decodeURIComponent(revoke[1]));if(bootstrap.some(a=>a.email===email))reject(409,'Os administradores principais não podem ser removidos por esta tela.');let accounts=await dynamicAccounts(env),found=false;accounts=accounts.map(a=>emailOf(a.email)===email?(found=true,{...a,active:false,revoked:now(),revokedBy:s.email}):a);if(!found)reject(404,'Acesso não encontrado.');await saveDynamicAccounts(env,accounts);await env.DB.prepare('DELETE FROM staff_sessions WHERE lower(email)=?').bind(email).run();return reply({ok:true})}
 const reset=path.match(/^\/staff\/access\/([^/]+)\/reset-pin$/);if(reset&&req.method==='POST'){const s=await member(req,env);if(!s||s.role!=='admin')reject(403,'Somente administradores podem redefinir PINs.');const email=emailOf(decodeURIComponent(reset[1]));if(bootstrap.some(a=>a.email===email))reject(409,'O PIN dos administradores principais é gerenciado na configuração principal.');let accounts=await dynamicAccounts(env),pin=makePin(),updated=null;for(const a of accounts)if(emailOf(a.email)===email&&a.active!==false){a.pinSalt=random();a.pinHash=await pinDigest(a.pinSalt,email,pin);updated=a;break}if(!updated)reject(404,'Acesso não encontrado.');await saveDynamicAccounts(env,accounts);await env.DB.prepare('DELETE FROM staff_sessions WHERE lower(email)=?').bind(email).run();return reply({ok:true,email,pin})}
 if(path==='/staff/renew'&&req.method==='POST'){const s=await member(req,env);if(!s||s.role!=='admin')reject(403,'Somente administradores podem liberar códigos antigos.');const b=await body(req),email=emailOf(b.email);if(!legacyAllowed(env,email))reject(400,'E-mail não autorizado no modo antigo.');await seed(env);if(await remaining(env,email)>0)reject(409,'Ainda existem códigos válidos para este e-mail');const row=await env.DB.prepare('SELECT max(generation) AS n FROM access_batches WHERE lower(email)=?').bind(email).first();const generation=(row?.n??0)+1,batch=email+':'+generation,codes=Array.from({length:6},()=>b64(crypto.getRandomValues(new Uint8Array(18)))),hashes=await Promise.all(codes.map(code=>digest(email+'\0'+code)));await env.DB.batch([env.DB.prepare('INSERT INTO access_batches (id,email,generation,created) VALUES (?,?,?,?)').bind(batch,email,generation,now()),...hashes.map(h=>env.DB.prepare('INSERT INTO access_codes (hash,email,batch,used) VALUES (?,?,?,NULL)').bind(h,email,batch))]);return reply({email,codes})}
 return null;
}
