import{ scrypt, timingSafeEqual }from'node:crypto';import{Buffer}from'node:buffer';import{b64}from'./push.js';
export const hashValue=async s=>b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
const random=()=>b64(crypto.getRandomValues(new Uint8Array(24))),fail=(status,message)=>{throw Object.assign(Error(message),{status})},json=(data,headers={})=>new Response(JSON.stringify(data),{headers:{'content-type':'application/json','cache-control':'no-store',...headers}}),emailOf=x=>String(x||'').trim().toLowerCase();
const tokenOf=req=>req.headers.get('cookie')?.match(/(?:^|;\s*)atrevida_account=([\w-]{43})(?:;|$)/)?.[1];
const derive=(password,salt)=>new Promise((resolve,reject)=>scrypt(password,salt,32,{N:32768,r:8,p:3,maxmem:64*1024*1024},(err,key)=>err?reject(err):resolve(key.toString('hex'))));
const validPassword=p=>{if(typeof p!=='string'||p.length<10||p.length>128)fail(400,'Use uma senha de 10 a 128 caracteres.')};
export async function account(req,env){const token=tokenOf(req);if(!token)return null;return env.DB.prepare('SELECT a.id,a.email,a.name,a.phone FROM customer_accounts a JOIN customer_sessions s ON s.account_id=a.id WHERE s.hash=? AND s.expires>?').bind(await hashValue(token),Date.now()).first()}
async function limit(req,env,email){const time=Math.floor(Date.now()/600000);for(const[key,max]of [['customer-ip:'+await hashValue(req.headers.get('cf-connecting-ip')||'unknown'),25],['customer-email:'+await hashValue(email),10]]){const r=await env.DB.prepare('INSERT INTO rate_limits (key,count,window) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window RETURNING count').bind(key,time).first();if(r.count>max)fail(429,'Muitas tentativas. Tente novamente em 10 minutos.')}}
async function session(env,a,data={}){const token=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare('INSERT INTO customer_sessions (hash,account_id,expires) VALUES (?,?,?)').bind(await hashValue(token),a.id,Date.now()+30*86400000).run();return json({account:{id:a.id,name:a.name,email:a.email,phone:a.phone},deliveryFee:699,...data},{'set-cookie':`atrevida_account=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`})}
export async function customers(req,env,path,body){
 if(path==='/customer/session'&&req.method==='GET'){const a=await account(req,env);const wallet=a?await env.DB.prepare('SELECT balance,completed FROM wallets WHERE owner=?').bind('account:'+a.id).first():null;return json({account:a,deliveryFee:a?699:899,wallet:wallet||{balance:0,completed:0}})}
 if(path==='/customer/logout'&&req.method==='POST'){const token=tokenOf(req);if(token)await env.DB.prepare('DELETE FROM customer_sessions WHERE hash=?').bind(await hashValue(token)).run();return json({ok:true},{'set-cookie':'atrevida_account=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
 if(['/customer/register','/customer/login','/customer/recover'].includes(path)&&req.method==='POST'){const b=await body(req),email=emailOf(b.email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)fail(400,'Informe um e-mail válido.');await limit(req,env,email);validPassword(b.password);
 const existing=await env.DB.prepare('SELECT * FROM customer_accounts WHERE email=?').bind(email).first();
 if(path==='/customer/register'){const name=String(b.name||'').trim().slice(0,80),phone=String(b.phone||'').replace(/\D/g,'');if(name.length<2||!/^\d{10,13}$/.test(phone)||b.accepted!==true)fail(400,'Confira nome, WhatsApp e aceite o uso dos dados para seu cadastro e pedidos.');if(existing)fail(409,'Não foi possível criar esta conta. Tente entrar ou recuperar o acesso.');const id=crypto.randomUUID(),salt=random(),recovery=random(),password=await derive(b.password,salt);try{await env.DB.prepare('INSERT INTO customer_accounts (id,email,name,phone,password,salt,recovery,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,email,name,phone,password,salt,await hashValue(recovery),Date.now()).run()}catch{fail(409,'Não foi possível criar esta conta. Tente entrar.')}return session(env,{id,email,name,phone},{recoveryCode:recovery})}
 if(path==='/customer/recover'){if(!existing||typeof b.recovery!=='string'||await hashValue(b.recovery.trim())!==existing.recovery)fail(403,'E-mail ou código de recuperação inválido.');const salt=random(),recovery=random(),password=await derive(b.password,salt);await env.DB.batch([env.DB.prepare('UPDATE customer_accounts SET password=?,salt=?,recovery=? WHERE id=?').bind(password,salt,await hashValue(recovery),existing.id),env.DB.prepare('DELETE FROM customer_sessions WHERE account_id=?').bind(existing.id)]);return session(env,existing,{recoveryCode:recovery})}
 const actual=await derive(b.password,existing?.salt||'atrevida-unavailable-account');if(!existing||!timingSafeEqual(Buffer.from(actual,'hex'),Buffer.from(existing.password,'hex')))fail(403,'E-mail ou senha incorretos.');return session(env,existing);
 }
 return null;
}
