import {member} from './access.js';
import {hashValue} from './customers.js';
const fail=(status,message)=>{throw Object.assign(Error(message),{status})};
const json=data=>new Response(JSON.stringify(data),{headers:{'content-type':'application/json','cache-control':'no-store'}});
export const tiers=[{km:2,fee:699},{km:4,fee:999},{km:6,fee:1299},{km:9,fee:1599},{km:12,fee:1799}];
export function deliveryPrice(meters,member=false,ranges=tiers){if(!Number.isFinite(meters)||meters<0||meters>ranges.at(-1).km*1000)fail(422,'Este endereço fica fora da entrega automática de até 12 km. Converse com a pizzaria.');const base=ranges.find(t=>meters<=t.km*1000).fee;return {base,fee:Math.max(699,base-(member?200:0)),discount:base-Math.max(699,base-(member?200:0))}}
const point=p=>p&&typeof p.lat==='number'&&typeof p.lng==='number'&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&p.lat>=-90&&p.lat<=90&&p.lng>=-180&&p.lng<=180?{lat:p.lat,lng:p.lng}:null;
const address=b=>({street:String(b.street||'').trim().slice(0,120),number:String(b.number||'').trim().slice(0,30),neighborhood:String(b.neighborhood||'').trim().slice(0,80),location:point(b.location)});
export async function deliverySettings(env){const r=await env.DB.prepare("SELECT data,updated FROM section_settings WHERE owner='store' AND section='delivery'").first();return {...(r?JSON.parse(r.data):{origin:null}),revision:r?.updated||0,ready:!!(r&&JSON.parse(r.data).origin&&env.GOOGLE_MAPS_API_KEY),mapsConnected:!!env.GOOGLE_MAPS_API_KEY,tiers:r?(JSON.parse(r.data).tiers||tiers):tiers,maxKm:r?(JSON.parse(r.data).tiers||tiers).at(-1).km:12,min:699,max:1799}}
async function googleJSON(url,options={}){try{const r=await fetch(url,{...options,signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();return await r.json()}catch{fail(503,'Não conseguimos consultar a rota agora. Tente novamente ou fale com a pizzaria; nenhum pedido foi enviado.')}}
export async function makeQuote(env,owner,b){const config=await deliverySettings(env);if(!config.ready)fail(503,'O cálculo de entrega está em configuração. Você pode escolher retirada ou consultar a pizzaria pelo WhatsApp.');const a=address(b);if(!a.street||!a.number||!a.neighborhood)fail(400,'Preencha rua, número e bairro para calcular a entrega.');let destination=a.location,formatted='';if(!destination){const q=new URL('https://maps.googleapis.com/maps/api/geocode/json');q.searchParams.set('address',`${a.street}, ${a.number}, ${a.neighborhood}, Luís Eduardo Magalhães, Bahia, Brasil`);q.searchParams.set('components','country:BR');q.searchParams.set('language','pt-BR');q.searchParams.set('key',env.GOOGLE_MAPS_API_KEY);const g=await googleJSON(q);const result=g.results?.[0];if(g.status!=='OK'||g.results?.length!==1||result.partial_match||!['ROOFTOP','RANGE_INTERPOLATED'].includes(result.geometry?.location_type))fail(422,'Não localizamos o endereço com precisão. Use sua localização estando no destino e confira o endereço.');destination=point(result.geometry.location);formatted=result.formatted_address||'';}if(!destination)fail(422,'Localização inválida.');const waypoint=p=>({location:{latLng:{latitude:p.lat,longitude:p.lng}}});const result=await googleJSON('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',headers:{'content-type':'application/json','X-Goog-Api-Key':env.GOOGLE_MAPS_API_KEY,'X-Goog-FieldMask':'routes.distanceMeters,routes.duration'},body:JSON.stringify({origin:waypoint(config.origin),destination:waypoint(destination),travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE',computeAlternativeRoutes:false,languageCode:'pt-BR',units:'METRIC'})});const route=result.routes?.[0];if(!Number.isFinite(route?.distanceMeters))fail(422,'Não encontramos uma rota de entrega para este endereço. Fale com a pizzaria.');const prices=deliveryPrice(route.distanceMeters,owner.startsWith('account:'),config.tiers);const quote={id:crypto.randomUUID(),expires:Date.now()+900000,addressHash:await hashValue(JSON.stringify(a)),revision:config.revision,location:destination,formattedAddress:formatted,distanceMeters:route.distanceMeters,durationSeconds:Number.parseInt(route.duration)||null,...prices,provider:'Google Maps',method:'route'};await env.DB.prepare("INSERT INTO section_settings(owner,section,data,updated) VALUES(?,'delivery_quote',?,?) ON CONFLICT(owner,section) DO UPDATE SET data=excluded.data,updated=excluded.updated").bind(owner,JSON.stringify(quote),Date.now()).run();const {addressHash,revision,...view}=quote;return view;}
export async function acceptQuote(env,owner,b){const row=await env.DB.prepare("SELECT data FROM section_settings WHERE owner=? AND section='delivery_quote'").bind(owner).first();const q=row&&JSON.parse(row.data),config=await deliverySettings(env);if(!q||q.id!==b.deliveryQuoteId||q.expires<Date.now()||q.revision!==config.revision||q.addressHash!==await hashValue(JSON.stringify(address(b))))fail(409,'Recalcule a entrega na revisão: o endereço, acesso ou prazo da cotação mudou.');return q;}
export async function deliveryRoutes(req,env,path,body){if(path!=='/staff/delivery')return null;if(!await member(req,env))fail(403,'Acesso exclusivo da equipe');if(req.method==='GET')return json(await deliverySettings(env));if(req.method==='PUT'){const b=await body(req),origin=point(b.origin);const ranges=b.tiers||(await deliverySettings(env)).tiers;if(!Array.isArray(ranges)||ranges.length<1||ranges.length>8||ranges.some((t,i)=>!Number.isFinite(t.km)||t.km<=0||t.km>50||!Number.isInteger(t.fee)||t.fee<699||t.fee>1799||(i>0&&(t.km<=ranges[i-1].km||t.fee<ranges[i-1].fee))))fail(400,'Confira as faixas crescentes de distância e taxa (R$ 6,99 a R$ 17,99).');if(!origin||b.confirmed!==true)fail(400,'Confirme a localização exata da pizzaria.');await env.DB.prepare("INSERT INTO section_settings(owner,section,data,updated) VALUES('store','delivery',?,?) ON CONFLICT(owner,section) DO UPDATE SET data=excluded.data,updated=excluded.updated").bind(JSON.stringify({origin,tiers:ranges}),Date.now()).run();return json(await deliverySettings(env))}return null;}
