const enc=new TextEncoder();
export const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export const un64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')),c=>c.charCodeAt(0));
const cat=(...a)=>{const o=new Uint8Array(a.reduce((n,x)=>n+x.length,0));let p=0;for(const x of a){o.set(x,p);p+=x.length}return o};
async function hkdf(secret,salt,info,n){const k=await crypto.subtle.importKey('raw',secret,'HKDF',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info},k,n*8))}
export function validEndpoint(endpoint){try{const u=new URL(endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.services.mozilla.com')||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.push.apple.com')||u.hostname==='wns2-paradise.notify.windows.com'||u.hostname.endsWith('.notify.windows.com'))}catch{return false}}
export async function encryptedPayload(sub,payload){const ua=un64(sub.keys.p256dh),auth=un64(sub.keys.auth);if(ua.length!==65||auth.length!==16)throw Error('Invalid subscription');const pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const as=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));const pub=await crypto.subtle.importKey('raw',ua,{name:'ECDH',namedCurve:'P-256'},false,[]);const shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:pub},pair.privateKey,256));const ikm=await hkdf(shared,auth,cat(enc.encode('WebPush: info\0'),ua,as),32);const salt=crypto.getRandomValues(new Uint8Array(16));const cek=await hkdf(ikm,salt,enc.encode('Content-Encoding: aes128gcm\0'),16);const nonce=await hkdf(ikm,salt,enc.encode('Content-Encoding: nonce\0'),12);const key=await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['encrypt']);const plain=cat(enc.encode(JSON.stringify(payload)),new Uint8Array([2]));if(plain.length>3000)throw Error('Payload too long');const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce},key,plain));return cat(salt,new Uint8Array([0,0,16,0,65]),as,cipher)}
export async function sendPush(env,sub,payload){if(!validEndpoint(sub.endpoint))throw Error('Invalid push destination');const header=b64(enc.encode(JSON.stringify({typ:'JWT',alg:'ES256'})));const claims=b64(enc.encode(JSON.stringify({aud:new URL(sub.endpoint).origin,exp:Math.floor(Date.now()/1000)+3600,sub:'https://pizzaria-atrevida-lem.mr-bruno01.chatgpt.site'})));const jwk=JSON.parse(env.VAPID_PRIVATE_JWK);const key=await crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const signature=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,enc.encode(header+'.'+claims));return fetch(sub.endpoint,{method:'POST',redirect:'error',headers:{Authorization:`vapid t=${header}.${claims}.${b64(signature)}, k=${env.VAPID_PUBLIC_KEY}`,TTL:'1800',Urgency:'high','Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream'},body:await encryptedPayload(sub,payload),signal:AbortSignal.timeout(10000)})}
export async function notify(env,audience,owner,payload){const query=audience==='staff'?env.DB.prepare('SELECT endpoint,data,owner FROM subscriptions WHERE audience = ?').bind('staff'):env.DB.prepare('SELECT endpoint,data,owner FROM subscriptions WHERE audience = ? AND owner = ?').bind('customer',owner);let rows=(await query.all()).results;if(audience==='staff'){const ids=JSON.parse(env.STAFF_ACCESS_CONFIG||'{"accounts":[]}').accounts.map(a=>'email:'+a.email);rows=rows.filter(r=>ids.includes(r.owner));}const results=await Promise.allSettled(rows.map(async r=>{const res=await sendPush(env,JSON.parse(r.data),payload);if(res.status===404||res.status===410)await env.DB.prepare('DELETE FROM subscriptions WHERE endpoint = ?').bind(r.endpoint).run();else if(!res.ok)throw Error('Push status '+res.status)}));return{targets:rows.length,accepted:results.filter(r=>r.status==='fulfilled').length}}
