import{member}from'./access.js';import{hashValue}from'./customers.js';import{b64}from'./push.js';
const json=x=>new Response(JSON.stringify(x),{headers:{'content-type':'application/json','cache-control':'no-store'}}),fail=(status,message)=>{throw Object.assign(Error(message),{status})},clean=(x,n=80)=>String(x||'').trim().slice(0,n),sections=['orders','kitchen','delivery','agenda','clients','access'];
const profile=d=>({slot:d.slot,name:d.name,phone:d.phone,vehicle:d.vehicle,active:!!d.active,photo:!!d.photo_key});
export async function driverIdentity(req,env){const slot=Number(req.headers.get('x-driver-slot')),token=req.headers.get('x-driver-token');if(!Number.isInteger(slot)||slot<1||slot>4||!token||token.length!==43)return null;return env.DB.prepare('SELECT * FROM drivers WHERE slot=? AND token_hash=? AND active=1').bind(slot,await hashValue(token)).first()}
export async function team(req,env,path,body){
 if(!/^\/(staff\/(preferences|drivers|accounts)|driver(?:\/|$)|orders\/[\w-]+\/assign)/.test(path))return null;
 const staff=await member(req,env),driver=await driverIdentity(req,env);
 if(path.startsWith('/staff/')||path.endsWith('/assign')){if(!staff)fail(403,'Entre na administração.')}else if(!driver&&!staff)fail(403,'Abra o link privado recebido da pizzaria.');
 if(path==='/staff/accounts'&&req.method==='GET'){const rows=await env.DB.prepare("SELECT a.id,a.name,a.email,a.phone,a.created,COALESCE(w.balance,0) AS balance,COALESCE(w.completed,0) AS completed FROM customer_accounts a LEFT JOIN wallets w ON w.owner='account:'||a.id ORDER BY a.created DESC LIMIT 200").all();return json({accounts:rows.results})}
 if(path==='/staff/preferences'&&req.method==='GET'){const r=await env.DB.prepare('SELECT section,data FROM section_settings WHERE owner=?').bind(staff.id).all();return json({settings:Object.fromEntries(r.results.map(x=>[x.section,JSON.parse(x.data)]))})}
 if(path.startsWith('/staff/preferences/')&&req.method==='PUT'){const section=path.split('/').at(-1);if(!sections.includes(section))fail(400,'Área inválida');const b=await body(req),data={title:clean(b.title,60),accent:['gold','green','blue','rose'].includes(b.accent)?b.accent:'gold',compact:b.compact===true,sort:b.sort==='oldest'?'oldest':'newest',filter:['active','all','received','quote','preparing','ready','onway','delivered','cancelled'].includes(b.filter)?b.filter:'active'};await env.DB.prepare('INSERT INTO section_settings(owner,section,data,updated) VALUES(?,?,?,?) ON CONFLICT(owner,section) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(staff.id,section,JSON.stringify(data),Date.now()).run();return json({ok:true,data})}
 if(path==='/staff/drivers'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM drivers ORDER BY slot').all();return json({drivers:r.results.map(profile)})}
 const slotMatch=path.match(/^\/staff\/drivers\/([1-4])(?:\/(link|photo))?$/);
 if(slotMatch){const slot=+slotMatch[1],existing=await env.DB.prepare('SELECT * FROM drivers WHERE slot=?').bind(slot).first();if(slotMatch[2]==='link'&&req.method==='POST'){if(!existing?.active)fail(400,'Salve e ative o perfil primeiro');const token=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare('UPDATE drivers SET token_hash=?,updated=? WHERE slot=?').bind(await hashValue(token),Date.now(),slot).run();return json({url:new URL(req.url).origin+'/entregador#'+slot+':'+token})}if(!slotMatch[2]&&req.method==='PUT'){const b=await body(req),name=clean(b.name,60),phone=clean(b.phone,20).replace(/\D/g,''),vehicle=clean(b.vehicle,60);if(!name)fail(400,'Informe o nome');await env.DB.prepare('INSERT INTO drivers(slot,name,phone,vehicle,active,updated) VALUES(?,?,?,?,?,?) ON CONFLICT(slot) DO UPDATE SET name=excluded.name,phone=excluded.phone,vehicle=excluded.vehicle,active=excluded.active,updated=excluded.updated').bind(slot,name,phone,vehicle,b.active===false?0:1,Date.now()).run();return json({ok:true})}}
 const assign=path.match(/^\/orders\/([\w-]{36})\/assign$/);if(assign&&req.method==='POST'){const b=await body(req),d=await env.DB.prepare('SELECT * FROM drivers WHERE slot=? AND active=1').bind(Number(b.slot)||0).first(),o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(assign[1]).first();if(!d||!o||JSON.parse(o.data).delivery!=='delivery'||['delivered','cancelled'].includes(o.status))fail(400,'Escolha um entregador ativo e um pedido de entrega em andamento.');await env.DB.batch([env.DB.prepare('INSERT INTO order_ops(order_id,driver_slot,courier_name,courier_vehicle) VALUES(?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET driver_slot=excluded.driver_slot,courier_name=excluded.courier_name,courier_vehicle=excluded.courier_vehicle').bind(o.id,d.slot,d.name,d.vehicle),env.DB.prepare('UPDATE orders SET courier_hash=NULL WHERE id=?').bind(o.id)]);return json({ok:true})}
 if(path==='/driver'&&req.method==='GET'){if(!driver)fail(403,'Link privado necessário');const rows=await env.DB.prepare("SELECT o.* FROM orders o JOIN order_ops p ON p.order_id=o.id WHERE p.driver_slot=? AND (o.status NOT IN ('delivered','cancelled') OR o.updated>?) ORDER BY o.created ASC LIMIT 100").bind(driver.slot,Date.now()-86400000).all();return json({profile:profile(driver),orders:rows.results.map(o=>{const d=JSON.parse(o.data),closed=['delivered','cancelled'].includes(o.status);return{id:o.id,status:o.status,created:o.created,total:o.total,eta:o.eta,confirmed:o.confirmed,data:closed?{}:{customer:d.customer,phone:d.phone,street:d.street,number:d.number,neighborhood:d.neighborhood,reference:d.reference,location:d.location,payment:d.payment,change:d.change,delivery:d.delivery}}})})}
 if(path==='/driver/profile'&&req.method==='PUT'){if(!driver)fail(403,'Link privado necessário');const b=await body(req),name=clean(b.name,60);if(!name)fail(400,'Informe seu nome');await env.DB.prepare('UPDATE drivers SET name=?,vehicle=?,updated=? WHERE slot=?').bind(name,clean(b.vehicle,60),Date.now(),driver.slot).run();return json({ok:true})}
 const photo=path.match(/^\/driver\/photo\/([1-4])$/);if(photo){const slot=+photo[1];if(!staff&&driver?.slot!==slot)fail(403,'Foto privada');const d=await env.DB.prepare('SELECT * FROM drivers WHERE slot=?').bind(slot).first();if(!d)fail(404,'Perfil não encontrado');if(req.method==='GET'){if(!d.photo_key||!env.UPLOADS)fail(404,'Sem foto');const object=await env.UPLOADS.get(d.photo_key);if(!object)fail(404,'Sem foto');return new Response(object.body,{headers:{'content-type':'image/jpeg','cache-control':'private, max-age=60','x-content-type-options':'nosniff'}})}if(req.method==='POST'){if(!env.UPLOADS)fail(503,'Fotos temporariamente indisponíveis');const text=await req.text();if(text.length>250000)fail(413,'Foto muito grande');let b;try{b=JSON.parse(text)}catch{fail(400,'Foto inválida')}if(typeof b.image!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(b.image))fail(400,'Use uma foto JPEG');const bytes=Uint8Array.from(atob(b.image.split(',')[1]),x=>x.charCodeAt(0));if(bytes.length>180000||bytes[0]!==255||bytes[1]!==216||bytes.at(-2)!==255||bytes.at(-1)!==217)fail(400,'Foto inválida');const key='drivers/'+crypto.randomUUID()+'.jpg';await env.UPLOADS.put(key,bytes,{httpMetadata:{contentType:'image/jpeg'}});await env.DB.prepare('UPDATE drivers SET photo_key=?,updated=? WHERE slot=?').bind(key,Date.now(),slot).run();if(d.photo_key)await env.UPLOADS.delete(d.photo_key);return json({ok:true})}}
 fail(404,'Área não encontrada');
}
