import {sql} from 'drizzle-orm';
import { sqliteTable,text,integer,index,uniqueIndex,check } from 'drizzle-orm/sqlite-core';
export const drafts=sqliteTable('drafts',{owner:text('owner').primaryKey(),data:text('data').notNull(),updated:integer('updated').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),owner:text('owner').notNull(),nonce:text('nonce').notNull(),data:text('data').notNull(),status:text('status').notNull(),knownTotal:integer('known_total').notNull(),total:integer('total'),created:integer('created').notNull(),updated:integer('updated').notNull(),confirmed:integer('confirmed'),eta:integer('eta'),events:text('events').notNull(),courierHash:text('courier_hash')},t=>[index('orders_owner_idx').on(t.owner),index('orders_status_created_idx').on(t.status,t.created),uniqueIndex('orders_nonce_idx').on(t.owner,t.nonce)]);
export const staff=sqliteTable('staff',{id:text('id').primaryKey(),email:text('email').notNull(),role:text('role').notNull(),created:integer('created').notNull()});
export const subscriptions=sqliteTable('subscriptions',{endpoint:text('endpoint').primaryKey(),owner:text('owner').notNull(),audience:text('audience').notNull(),data:text('data').notNull(),updated:integer('updated').notNull()},t=>[index('subscriptions_owner_idx').on(t.owner),index('subscriptions_audience_idx').on(t.audience)]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),window:integer('window').notNull()});
export const accessBatches=sqliteTable('access_batches',{id:text('id').primaryKey(),email:text('email').notNull(),generation:integer('generation').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('access_batch_generation').on(t.email,t.generation)]);
export const accessCodes=sqliteTable('access_codes',{hash:text('hash').primaryKey(),email:text('email').notNull(),batch:text('batch').notNull(),used:text('used')},t=>[index('access_codes_email').on(t.email)]);
export const staffSessions=sqliteTable('staff_sessions',{hash:text('hash').primaryKey(),email:text('email').notNull(),expires:integer('expires').notNull()},t=>[index('staff_sessions_expiry').on(t.expires)]);
export const orderOps=sqliteTable('order_ops',{orderId:text('order_id').primaryKey(),note:text('note'),courierName:text('courier_name'),courierVehicle:text('courier_vehicle'),trackingHash:text('tracking_hash'),driverSlot:integer('driver_slot')});
export const customerAccounts=sqliteTable('customer_accounts',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),phone:text('phone').notNull(),password:text('password').notNull(),salt:text('salt').notNull(),recovery:text('recovery').notNull(),created:integer('created').notNull()});
export const customerSessions=sqliteTable('customer_sessions',{hash:text('hash').primaryKey(),accountId:text('account_id').notNull(),expires:integer('expires').notNull()},t=>[index('customer_sessions_account').on(t.accountId)]);
export const sectionSettings=sqliteTable('section_settings',{owner:text('owner').notNull(),section:text('section').notNull(),data:text('data').notNull(),updated:integer('updated').notNull()},t=>[uniqueIndex('section_settings_owner').on(t.owner,t.section)]);
export const drivers=sqliteTable('drivers',{slot:integer('slot').primaryKey(),name:text('name').notNull(),phone:text('phone').notNull(),vehicle:text('vehicle').notNull(),photoKey:text('photo_key'),tokenHash:text('token_hash'),active:integer('active').notNull().default(1),updated:integer('updated').notNull()});

export const wallets = sqliteTable('wallets', {owner:text('owner').primaryKey(),balance:integer('balance').notNull().default(0),completed:integer('completed').notNull().default(0)},t=>[check('wallet_nonnegative',sql`${t.balance} >= 0`)]);
